### ISSUE TITLE
Is there a way to make localization? 

### ISSUE THREAD

**Issue by andkirby** [openpim/web#2]
Hi there,

I'd like to have a multilanguage database. Is there a way to make it?

Thanks

**Comment by openpim** [comment]
Hi,

System supports values on different languages out of the box. You can add language in configuration and you will have ability to store values for different languages 

![image](https://user-images.githubusercontent.com/71308573/132526880-b1e5386d-d4f0-4dd3-82b4-4ed939d6d56b.png)

But this is for values. You can also localize the UI itself, this will require providing a property file for corresponding language.
Let's have a call and I can describe everything for you in more details. Just drop me an email at team@openpim.org and we can arrange a call.

**Comment by andkirby** [comment]
Thanks, Slava, for the expanded answer. Yeah, I'm looking for values “translation” at this stage.
For the moment it's enough to have English, but probably it would require “local” language for other teammates.
