### ISSUE TITLE
"Roles are not loaded !!!" JS error

### ISSUE THREAD

**Issue by andkirby** [openpim/web#3]
Hi @openpim

It's hard to provide steps to reproduce, but after a while the system adds the JS error:
```
users.js:141 Roles are not loaded !!!
```
Settings menu item disappears in the left navigation.

### UPD

It seems when I remove an object type which cannot be removed, it gets to be broken.

**Comment by openpim** [comment]
Hi @andkirby,

Thanks, this is known issue and we will fix it. You can perform "cold" page refresh in web browser to return back to normal state. Usually you can make "cold" refresh by clicking at refresh button when pressing CTRL+SHIFT.

So this is not a blocker, but must be fixed for sure.

**Comment by openpim** [comment]
Fix for this issue - https://github.com/openpim/web/commit/db5db4348254fc1044c3ac54298035b8ba48037e
It will be in production when version 1.4 will be delivered.

**Comment by andkirby** [comment]
Thank you!

**Comment by openpim** [comment]
Please do not forget to use new version (docker image version 1.4)
