### ISSUE TITLE
Adding multiple values into list of values causes performance issues

### ISSUE THREAD

**Issue by mantasdeksnys** [openpim/web#30]
I've noticed an issue using LOVs. Adding more than 10 values into the list causes huge degradation of browser's performance to an extent where it becomes impossible to work using the graphical interface.
![image](https://github.com/openpim/web/assets/2671930/ad096543-db8b-4fa8-894d-e0fe2c64bdb2)

**Comment by openpim** [comment]
Hi @mantasdeksnys this looks strange because we have projects with more then thousand of values in the list and it is working fine. Is it possible that you can send us DB dump of your database? Please send us it to team@openpim.org and we will be able to take a look ourselves.

**Comment by mantasdeksnys** [comment]
Thank you @openpim. After reading your comment I've tested this again with Google Chrome Version 114.0.5735.199 (Official Build) (64-bit) and it works with dozen values as expected there. I've initially experienced the issue using Microsoft Edge Version 114.0.1823.82 (Official build) (64-bit), so it might be incompatibility with the browser. Regardless, using a different browser solved my problem, so I believe the issue can be closed.
