### ISSUE TITLE
The system removes an object type when it cannot be removed

### ISSUE THREAD

**Issue by andkirby** [openpim/web#4]
## STR:
1. Create the object type AAA.
2. Create an attribute and make assignment to this type AAA.
3. Get back to the type AAA and try to remove.

### Actual:
After confirmation, the system will remove the item from UI and show an error.
Page refresh may help to recover it.

### Expected:
1. (improvement) The system asks the user in advance about breaking relationship with attributes. After confirmation, it completely removes the object type.
2. The system will show just an error without removing the item from UI.

## Background
Actually, I'd like to have an option to 
- change Identifier
- move an object type like a folder (at least if they do not have records).
Just trying to reorganize entities.

**Comment by openpim** [comment]
Thanks, issue is noted.

Regarding changing identifier this is good idea, but hard to implement now because we have a lot of dependencies for it. But I will this to the plan.

And also the same for moving object types.

**Comment by openpim** [comment]
fixed. Please do not forget to use new version (docker image version 1.4)
